{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "INFRA RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 1, "y": 0 },
   "targets": [
    {
     "expr": "total_alloc_memory{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"}",
     "legendFormat": "Total RAM in GB"
    }
   ]
  },
  {
   "title": "INFRA CPU Metrics",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "total_alloc_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"}",
     "legendFormat": "Total CPU cores"
    }
   ]
  },
  {
   "title": "Infra memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_memory{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"}",
     "legendFormat": "total_memory"
    }
   ]
  },
  {
   "title": "Infra memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_memory{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"} - total_alloc_memory{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"}",
     "legendFormat": "total_available_memory"
    }
   ]
  },
  {
   "title": "Infra VCPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"}",
     "legendFormat": "total_cores"
    }
   ]
  },
  {
   "title": "Infra VCPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"} - total_alloc_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\"}",
     "legendFormat": "available_cores"
    }
   ]
  },
  {
   "title": "Tenant Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"admin\"}",
     "legendFormat": "admin"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"BMASenm02\"}",
     "legendFormat": "BMASenm02"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"alt_demo\"}\t",
     "legendFormat": "alt_demo"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"enm01xaas\"}\t",
     "legendFormat": "enm01xaas"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"frstagingenm01\"}\t",
     "legendFormat": "frstagingenm01"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"frstagingenm02\"}\t",
     "legendFormat": "frstagingenm02"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"genie\"}\t",
     "legendFormat": "genie"
    },
    {
     "expr": "tenant_ram{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"genie_pipeline\"}\t",
     "legendFormat": "genie_pipeline"
    }
   ]
  },
  {
   "title": "Tenant VPU limits",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"admin\"}",
     "legendFormat": "admin"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"BMASenm02\"}",
     "legendFormat": "BMASenm02"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"alt_demo\"}\t",
     "legendFormat": "alt_demo"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"enm01xaas\"}\t",
     "legendFormat": "enm01xaas"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"frstagingenm01\"}\t",
     "legendFormat": "frstagingenm01"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"frstagingenm02\"}\t",
     "legendFormat": "frstagingenm02"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"genie\"}\t",
     "legendFormat": "genie"
    },
    {
     "expr": "tenant_vcpu{instance=\"192.168.253.17:8081\",job=\"custom_expoter\",name=\"genie_pipeline\"}\t",
     "legendFormat": "genie_pipeline"
    }
   ]
  }
 ]
}